# Generated by Django 4.2 on 2023-06-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_image3_product_image4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
